#!/usr/bin/env bash
# Check the number of command-line arguments passed to the script
if [ $# -lt 3 ];
then
    # If fewer than 3 arguments are provided, print a usage message and exit.
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit
fi

# Check if a fourth argument (SSH key path) is provided
if [ $# -ge 4 ];
then
   
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
 
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
