#!/usr/bin/env bash
# Bash script to install and configure HAProxy

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
echo 'frontend haproxy_loadbalancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server [STUDENT_ID]-web-01 100.25.33.181:80 check
    server [STUDENT_ID]-web-02 100.27.12.71:80 check
' | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply changes
sudo service haproxy restart
