#!/usr/bin/env bash
# This script kills the 4-to_infinity_and_beyond process.

# Use 'pgrep' with '-f' option to find the PID of the process based on its name
# Then use 'kill' to terminate the process
kill "$(pgrep -f 4-to_infinity_and_beyond)"
