#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
# Read /etc/passwd line by line and extract required information
while IFS=: read -r username _ uid _ _ home _; do
  echo "Username: $username"
  echo "User ID: $uid"
  echo "Home Directory: $home"
done < /etc/passwd
