#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
# Use awk to extract the IP and HTTP status code from the Apache log file
awk '{print $1, $9}' apache-access.log
