#!/usr/bin/env bash
# Displays 'Best School' in stdout 10 times using a while loop
# Initialize the counter
counter=1

# Loop using while loop
while [ $counter -le 10 ]
do
  echo "Best School"
  (( counter++ ))
done
