#!/usr/bin/env bash
#A Bash script that displays Best School 10 times
# Initialize the counter
counter=0

# Loop using until loop
until [ $counter -ge 10 ]
do
  echo "Best School"
  (( counter++ ))
done
