#!/usr/bin/env bash
#A Bash script that displays Best School 10 times
# Initialize the counter
counter=1

# Loop using while loop
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi

  (( counter++ ))
done
