#!/usr/bin/env bash

# Initialize the counter
counter=1

# Loop using while loop
while [ $counter -le 10 ]
do
  if [ $counter -eq 4 ]; then
    echo "bad luck"
  elif [ $counter -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  (( counter++ ))
done
