#!/usr/bin/env bash
#Write a Bash script that displays:The content of the current directoryIn a list format
# Loop through the files in the current directory
for file in *; do
  # Check if the file is not a hidden file (does not start with a dot)
  if [[ $file != .* ]]; then
    # Extract the part of the name after the first dash
    name_after_dash="${file#*-}"

    # Display the extracted name
    echo "$name_after_dash"
  fi
done
